baseurl = "/"
languageCode = "en-us"
languageLang = "en"
title = "e3b0c442"
theme = "hyde"

# RSS, categories and tags disabled for an easy start
# See configuration options for more details: 
# https://gohugo.io/getting-started/configuration/#toml-configuration
disableKinds = ["RSS", "taxonomy", "taxonomyTerm"]

[params]
  description = "Rants and ramblings of a bit mangler and electron herder."
  copyright = "Â©2018 Nick. 85E3 8F69 046B 44C1 EC9F  B07B 76D7 8F05 00D0 26C4"