baseurl = "/"
languageCode = "en-us"
languageLang = "en"
title = "e3b0c442"
theme = "hyde"

# RSS, categories and tags disabled for an easy start
# See configuration options for more details: 
# https://gohugo.io/getting-started/configuration/#toml-configuration
disableKinds = ["RSS", "taxonomy", "taxonomyTerm"]

[params]
  description = "Rants and ramblings of a bit mangler and electron herder"
  copyright = "Â©2018 Nick. 9408 6361 4B0B 3307 5068 5FE8 DD3F EC7C 659D CEA2"